PKG_NAME = confuse
PKG_VERS = 3.2.1
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)                                                                              
PKG_DIST_SITE = https://github.com/martinh/libconfuse/releases/download/v$(PKG_VERS)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = https://github.com/martinh/libconfuse
COMMENT  = Small configuration file parser library for C.
LICENSE  = https://raw.githubusercontent.com/martinh/libconfuse/v$(PKG_VERS)/LICENSE

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
