PKG_NAME = libantlr3c
PKG_VERS = 3.4
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)                                                                              
PKG_DIST_SITE = http://www.antlr3.org/download/C
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

HOMEPAGE = http://www.antlr3.org/
COMMENT  = ANTLR, ANother Tool for Language Recognition, is a language tool that provides a framework for constructing recognizers, interpreters, compilers, and translators from grammatical descriptions containing actions in a variety of target languages.

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
